# Generated by Django 4.1.7 on 2025-01-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="base_currency",
            field=models.CharField(
                blank=True,
                default="USD",
                max_length=10,
                null=True,
                verbose_name="Base Currency",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("freelancing", "Freelancing"),
                    ("ngo", "NGO"),
                    ("profit_business", "Profit Business"),
                ],
                default="profit_business",
                max_length=50,
                null=True,
                verbose_name="Business Type",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="date_format",
            field=models.CharField(
                blank=True,
                default="YYYY-MM-DD",
                max_length=20,
                null=True,
                verbose_name="Date Format",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_template_id",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="Default Template ID"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="invoice_expiry_days",
            field=models.IntegerField(
                blank=True, default=30, null=True, verbose_name="Invoice Expiry Days"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="invoice_reference_prefix",
            field=models.CharField(
                blank=True,
                default="INV",
                max_length=10,
                null=True,
                verbose_name="Invoice Reference Prefix",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="note",
            field=models.TextField(
                blank=True, default="Additional notes.", null=True, verbose_name="Note"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="terms_and_conditions",
            field=models.TextField(
                blank=True,
                default="Default terms and conditions.",
                null=True,
                verbose_name="Terms and Conditions",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="theme_color",
            field=models.CharField(
                blank=True,
                default="blue",
                max_length=20,
                null=True,
                verbose_name="Theme Color",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="time_zone",
            field=models.CharField(
                blank=True,
                default="UTC",
                max_length=50,
                null=True,
                verbose_name="Time Zone",
            ),
        ),
    ]
