# Generated by Django 4.1.7 on 2024-12-01 18:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "organization",
            "0003_alter_organization_address_alter_organization_email_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrganizationRole",
            new_name="OrganizationMember",
        ),
    ]
