# Generated by Django 4.1.7 on 2025-01-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_organization_base_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="invoice_reference_prefix",
            field=models.CharField(
                blank=True,
                default="",
                max_length=10,
                null=True,
                verbose_name="Invoice Reference Prefix",
            ),
        ),
    ]
