# Generated by Django 4.1.7 on 2024-12-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("email", "organization_id"),
                name="unique_email_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("phone_number", "organization_id"),
                name="unique_phone_number_per_organization",
            ),
        ),
    ]
