# Generated by Django 4.1.7 on 2024-12-15 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="client",
            old_name="organization",
            new_name="organization_id",
        ),
    ]
