# Generated by Django 4.1.7 on 2025-01-03 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "pkid",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "ref_no",
                    models.CharField(max_length=50, verbose_name="Reference Number"),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("items", models.JSONField(verbose_name="Invoice Items")),
                ("payment_info", models.JSONField(verbose_name="Payment Info")),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tax"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="client.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-updated_at"],
                "abstract": False,
            },
        ),
    ]
