# Generated by Django 4.1.7 on 2024-11-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="subtotal",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Client Details"
            ),
        ),
    ]
