# Generated by Django 4.1.7 on 2025-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="note",
            field=models.TextField(
                blank=True, default="Additional notes.", null=True, verbose_name="Note"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="terms_and_conditions",
            field=models.TextField(
                blank=True,
                default="Default terms and conditions.",
                null=True,
                verbose_name="Terms and Conditions",
            ),
        ),
    ]
