# Generated by Django 4.1.7 on 2024-11-26 05:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0002_remove_invoice_subtotal_alter_invoice_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="total",
        ),
    ]
