# Generated by Django 4.1.7 on 2025-01-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0003_invoice_note_invoice_terms_and_conditions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="ref_no",
        ),
        migrations.AddField(
            model_name="invoice",
            name="irn",
            field=models.CharField(
                blank=True,
                max_length=255,
                unique=True,
                verbose_name="Invoice Reference Number",
            ),
        ),
    ]
