# Generated by Django 4.1.7 on 2025-01-11 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0005_alter_invoice_client_alter_invoice_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="date",
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 10, 8, 35, 18, 389532),
                verbose_name="Due Date",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(
                default=datetime.datetime.now, verbose_name="Issue Date"
            ),
        ),
    ]
