# Generated by Django 4.1.7 on 2025-01-11 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0006_remove_invoice_date_invoice_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 10, 8, 50, 15, 889831),
                verbose_name="Due Date",
            ),
        ),
    ]
