# Generated by Django 4.1.7 on 2025-01-11 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0007_alter_invoice_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 10, 8, 53, 4, 941245),
                verbose_name="Due Date",
            ),
        ),
    ]
