# Generated by Django 4.1.7 on 2025-01-11 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0008_alter_invoice_due_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="tax",
        ),
        migrations.AddField(
            model_name="invoice",
            name="discount",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Discount"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 10, 14, 10, 41, 258381),
                verbose_name="Due Date",
            ),
        ),
    ]
