# Generated by Django 4.1.7 on 2025-01-11 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0009_remove_invoice_tax_invoice_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 10, 14, 21, 40, 669413),
                verbose_name="Due Date",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="title",
            field=models.CharField(
                default="Invoice", max_length=255, verbose_name="Title"
            ),
        ),
    ]
