# Generated by Django 4.1.7 on 2025-01-14 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0010_alter_invoice_due_date_alter_invoice_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="logo_url",
            field=models.URLField(
                blank=True, max_length=255, null=True, verbose_name="Logo URL"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 13, 22, 0, 58, 258567),
                verbose_name="Due Date",
            ),
        ),
    ]
