# Generated by Django 4.1.7 on 2025-01-17 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0011_invoice_logo_url_alter_invoice_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="template_id",
            field=models.IntegerField(default=1, verbose_name="Template ID"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 16, 9, 46, 51, 16547),
                verbose_name="Due Date",
            ),
        ),
    ]
