# Generated by Django 4.1.7 on 2025-01-17 11:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_alter_organization_invoice_reference_prefix"),
        ("client", "0002_initial"),
        ("invoice", "0012_invoice_template_id_alter_invoice_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="client.client",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 16, 14, 43, 39, 723939),
                verbose_name="Due Date",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="organization.organization",
            ),
        ),
    ]
