# Generated by Django 4.1.7 on 2025-01-23 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoice", "0013_alter_invoice_client_alter_invoice_due_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="shipping",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                null=True,
                verbose_name="Shipping",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                default=datetime.datetime(2025, 2, 22, 18, 31, 51, 125849),
                verbose_name="Due Date",
            ),
        ),
    ]
